kind: pipeline
type: docker
name: greeting

steps:
- name: docker
  pull: if-not-exists
  image: plugins/docker
  settings:
    repo: registry.3l8.ru/lissteron/imageresizer
    registry: registry.3l8.ru
    auto_tag: true


